emicro_core_employees:
    pattern:  /
    defaults: { _controller: EmicroCoreBundle:Employee:index }

emicro_core_employees_test:
    pattern:  /employees/test
    defaults: { _controller: EmicroCoreBundle:Employee:test }


emicro_core_employees_create:
    pattern:  /employee/create
    defaults: { _controller: EmicroCoreBundle:Employee:create }

emicro_core_employees_edit:
    pattern:  /employee/edit/{id}
    defaults: { _controller: EmicroCoreBundle:Employee:edit }
    requirements:
          id:  \d+