parameters:
#    emicro_test.example.class: Emicro\Bundle\TestBundle\Example

services:
#    emicro_test.example:
#        class: %emicro_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
