<?php

namespace Emicro\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{

    public function prepareAddress(Address $addressData)
    {
        if (is_null($addressData->getId())) {
            $address = new Address();
        } else {
            $address = $this->find($addressData->getId());
        }

        $address->setStreet($addressData->getStreet());
        $address->setCity($addressData->getCity());
        $address->setState($addressData->getState());
        $address->setPostalCode($addressData->getPostalCode());
        $address->setCountry($addressData->getCountry());
        $address->setIsPresent($addressData->getIsPresent());

        return $address;
    }
}
