<?php

namespace Emicro\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->findAll();
    }

    public function create($data)
    {
        $employee = $this->prepareEmployee($data);

        $address  = $this->_em->getRepository("EmicroCoreBundle:Address")->prepareAddress($data->getAddresses());
        $address->setEmployee($employee);

        $this->_em->persist($employee);
        $this->_em->persist($address);
        $this->_em->flush();
    }

    public function prepareEmployee(Employee $employeeData)
    {
        if (is_null($employeeData->getId())) {
            $employee = new Employee();
        } else {
            $employee = $this->find($employeeData->getId());
        }

        $employee->setFirstName($employeeData->getFirstName());
        $employee->setLastName($employeeData->getLastName());
        $employee->setDesignation($employeeData->getDesignation());
        $employee->setEmail($employeeData->getEmail());
        $employee->setContactNumber($employeeData->getContactNumber());

        return $employee;
    }


}
